# Memulai Python!
**Pertemuan 4**

In [3]:
print("Hellow")

Hellow


In [4]:
tinggi = 155
berat = 90.3
print(berat)

90.3


In [5]:
dataIus = ["Tinggi", 170, "Berat", 90.3]
print(dataIus)

['Tinggi', 170, 'Berat', 90.3]


In [18]:
tinggi = [180,181,182]
print(tinggi)

[180, 181, 182]


In [19]:
berat = [60,70,90]
print(berat)

[60, 70, 90]


## Install Library Numpy

In [7]:
pip install numpy

You should consider upgrading via the 'C:\Python39\python.exe -m pip install --upgrade pip' command.


In [20]:
import numpy as np

np_tinggi = np.array(tinggi)
np_berat = np.array(berat)

In [21]:
np_tinggi

array([180, 181, 182])

In [22]:
np_berat

array([60, 70, 90])

In [23]:
berat_ideal = np_berat/np_tinggi ** 2

In [24]:
berat_ideal

array([0.00185185, 0.00213669, 0.00271706])

In [25]:
type(berat_ideal)

numpy.ndarray

## Instalasi Library SCIPY

In [26]:
pip install scipy

You should consider upgrading via the 'C:\Python39\python.exe -m pip install --upgrade pip' command.


## Instalasi Library Pandas

In [27]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.Collecting pandas


You should consider upgrading via the 'C:\Python39\python.exe -m pip install --upgrade pip' command.


In [28]:
import pandas as pd

In [29]:
dataTab = pd.read_csv("Tab.csv")

In [30]:
dataTab

Unnamed: 0     Negara  Populasi    Area    Ibukota
0         IN  Indonesia       250  123456    Jakarta
1         MA   Malaysia        25    3456         KL
2         SI  Singapura        15     456  Singapura
3         JP     Jepang        60    5678      Tokyo
4         TH   Thailand        45     678    Bangkok

In [31]:
dataTab["Negara"]

0    Indonesia
1     Malaysia
2    Singapura
3       Jepang
4     Thailand
Name: Negara, dtype: object

In [32]:
dataTab.Negara

0    Indonesia
1     Malaysia
2    Singapura
3       Jepang
4     Thailand
Name: Negara, dtype: object